services:
  accounts:
     image: "tahmidhassanhridoy/accounts:s4"
     container_name: accounts-ms
     ports:
       - "8080:8080"
     deploy:
       resources:
         limits:
           memory: 700m
     networks:
       - tahmidBank
  loans:
    image: "tahmidhassanhridoy/loans:s4"
    container_name: loans-ms
    ports:
      - "8080:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tahmidBank
  cards:
    image: "tahmidhassanhridoy/cards:s4"
    container_name: cards-ms
    ports:
      - "9080:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tahmidBank
networks:
  tahmidBank:
    driver: "bridge"